### ISSUE TITLE
L2 targeted attack taking very much query with low success rate 

### ISSUE THREAD

**Issue by as791** [max-andr/square-attack#10]
I am applying the square l2 targeted attack on ImageNet dataset with VGG16 model, for n_ex=100, with p=0.05, n_iter=20000, eps=1275/255. First of my concern is that the attack sometimes starts with "nan" med#q_ae and avg#q_ae and second that it is taking 7k queries and also gives a success rate of only 61%.

**Comment by fra31** [comment]
Hi,

thanks for the interest in our work! The "nan" as median and mean number of queries should be due to the fact that at the beginning the success rate is 0% and then the statistics are computed on empty arrays. You should get positive numbers as soon as some adversarial examples are found.

We discuss targeted attacks in Section E.1 of our paper.
Note that in general the budget of queries for targeted attacks is higher than for untargeted ones, since the task is more challenging (in literature, 50k-100k queries are used). Moreover, we noticed that for Square Attack smaller values of `p` work better for targeted attacks (see paper).
In the paper we report a success rate of 66.5% on Inception-v3 (which is in general more robust than VGG16) with 60k queries and `p=0.02`. Given that you used less queries and larger `p`, I think that the results you got are roughly in line with what expected, and using more queries and smaller `p` should improve them.

Hope this helps!

**Comment by as791** [comment]
Thanks for the clarification, this helped.
