### ISSUE TITLE
The Linf version

### ISSUE THREAD

**Issue by bymavis** [max-andr/square-attack#6]
Hi, I am glad to learn from this interesting work. I got one question here. In attack.py Line#238, why do you add deltas on the variable, x_curr, instead of x_best_curr? Thanks a lot.

**Comment by max-andr** [comment]
Hi,

Because [here](https://github.com/max-andr/square-attack/blob/master/attack.py#L223) we define `deltas` as `deltas = x_best_curr - x_curr`. So it is the difference between `x_best` and `x` for some particular indices `idx_to_fool`.

And what we do [here](https://github.com/max-andr/square-attack/blob/master/attack.py#L236), we modify this difference  to be +eps or -eps in some square-shaped region.

I think it's a bit confusing that in the code we call as `deltas` the adversarial **perturbation**, while in the paper `delta` rather refers to the **sampled update**:
![image](https://user-images.githubusercontent.com/14852704/91085384-ac8ccb80-e64d-11ea-80db-0a1d4cc27921.png)
Sorry for this discrepancy :) I guess it can lead to some confusion.

I hope that helps.

Best,
Maksym

**Comment by bymavis** [comment]
Okay, I got that. Thanks for your kind reply.
